api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            max_age: 0            # max-age=0
            stale_if_error: 86400 # stale-if-error=86400
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
    swagger:
        http_auth:
            clerk:
                scheme: bearer
                bearerFormat: Clerk Session Token
    http_cache:
        invalidation:
            enabled: true
            urls: []
            purger: 'api_platform.http_cache.purger.varnish.xkey'
