api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
    swagger:
        http_auth:
            clerk:
                scheme: bearer
                bearerFormat: Clerk Session Token
